### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by reinaldoacdc** [Moebios-Softwares/CommerceERP#2]
Bacana a iniciativa, vi lá no Forum AcBr. 

O que acha de abrir o Discussions para conversar sobre alguns pontos do repositório?

Pensa em usar algum ORM  no projeto ?

**Comment by arthur-moebios** [comment]
Olá! Tudo bem?Acho ótimo! Acho que o ORM seria o ideal. Mas nunca usei em Delphi. Vou abrir lá pra discutirmos e propormos as coisas 😁Enviado do meu iPhoneEm 15 de fev. de 2023, à(s) 18:46, Reinaldo Alberto ***@***.***> escreveu:﻿
Bacana a iniciativa, vi lá no Forum AcBr.
O que acha de abrir o Discussions para conversar sobre alguns pontos do repositório?
Pensa em usar algum ORM  no projeto ?

**Comment by arthur-moebios** [comment]
Discussions disponível!
